### ISSUE TITLE
Support for LDAP logins

### ISSUE THREAD

**Issue by Aaranaw** [FallingSnow/lightdm-webkit2-material2#3]
Hi, wanted to give this a go however I noticed in the readme that it says user choice from a dropdown box, is there any way to specify the user as my account is not a local one but rather an LDAP login that required DOMAIN\username login.

Thanks.

**Comment by FallingSnow** [comment]
Currently LDAP login isn't supported, but it shouldn't be too hard to add. I just need to allow the user to specify a username rather than selecting one. There are a couple of things you will need to do to allow [lightdm](https://wiki.contribs.org/Client_Authentication:Ubuntu_via_sssd/ldap#LightDM_Login_Box) and [pam](https://wiki.archlinux.org/index.php/LDAP_authentication) to do ldap authentication.

I'll add this feature as soon as I can but in the mean time make sure you have done the steps above.

**Comment by FallingSnow** [comment]
I have not tested it yet but please try the latest git and let me know if it works.

**Comment by Aaranaw** [comment]
Thanks, giving it a go now.

**Comment by FallingSnow** [comment]
Did you ever get this working?

**Comment by Aaranaw** [comment]
Hi, unfortunately not, trying to figure out why I am getting an error message about default theme but have not had the time to troubleshoot.

**Comment by FallingSnow** [comment]
Going to close this issue for the time being then. Reopen it if the issue persists.
